### ISSUE TITLE
Security Slam 2023 umbrella issue

### ISSUE THREAD

**Issue by matthyx** [kubescape/kubevuln#156]
### Summary

**Repository**: kubevuln
**URL**: https://github.com/kubescape/kubevuln
**Checks sets**:  `CODE`
**Score**: 56

### Checks passed per category

| Category       |                                           Score |
| :------------- | ----------------------------------------------: |
| Documentation  |  76% |
| License        |        75% |
| Best Practices | 31% |
| Security       |       42% |
| Legal          |          n/a |

### Documentation [76%]

  - [ ] Changelog ([_docs_](https://clomonitor.io/docs/topics/checks/#changelog))
  - [x] [Contributing](https://github.com/kubescape/kubevuln/blob/main/CONTRIBUTING.md) ([_docs_](https://clomonitor.io/docs/topics/checks/#contributing))
  - [ ] Maintainers ([_docs_](https://clomonitor.io/docs/topics/checks/#maintainers))
  - [x] [Readme](https://github.com/kubescape/kubevuln/blob/main/README.md) ([_docs_](https://clomonitor.io/docs/topics/checks/#readme))
  
### License [75%]

  - [x] Apache-2.0 ([_docs_](https://clomonitor.io/docs/topics/checks/#spdx-id))
  - [x] Approved license ([_docs_](https://clomonitor.io/docs/topics/checks/#approved-license))
  - [ ] License scanning ([_docs_](https://clomonitor.io/docs/topics/checks/#license-scanning))
  
### Best Practices [31%]

  - [ ] Artifact Hub badge ([_docs_](https://clomonitor.io/docs/topics/checks/#artifact-hub-badge))
  - [x] Contributor License Agreement ([_docs_](https://clomonitor.io/docs/topics/checks/#contributor-license-agreement)) `EXEMPT`
  - [x] Developer Certificate of Origin ([_docs_](https://clomonitor.io/docs/topics/checks/#developer-certificate-of-origin))
  - [ ] OpenSSF best practices badge ([_docs_](https://clomonitor.io/docs/topics/checks/#openssf-badge))
  - [ ] OpenSSF Scorecard badge ([_docs_](https://clomonitor.io/docs/topics/checks/#openssf-scorecard-badge))
  - [x] [Recent release](https://github.com/kubescape/kubevuln/releases/tag/v0.2.110) ([_docs_](https://clomonitor.io/docs/topics/checks/#recent-release))
  
### Security [42%]

  - [x] Binary artifacts ([_docs_](https://clomonitor.io/docs/topics/checks/#binary-artifacts-from-openssf-scorecard))
  - [x] Code review ([_docs_](https://clomonitor.io/docs/topics/checks/#code-review-from-openssf-scorecard))
  - [x] Dangerous workflow ([_docs_](https://clomonitor.io/docs/topics/checks/#dangerous-workflow-from-openssf-scorecard))
  - [ ] Dependencies policy ([_docs_](https://clomonitor.io/docs/topics/checks/#dependencies-policy))
  - [ ] Dependency update tool ([_docs_](https://clomonitor.io/docs/topics/checks/#dependency-update-tool-from-openssf-scorecard))
  - [x] Maintained ([_docs_](https://clomonitor.io/docs/topics/checks/#maintained-from-openssf-scorecard))
  - [ ] Software bill of materials (SBOM) ([_docs_](https://clomonitor.io/docs/topics/checks/#software-bill-of-materials-sbom))
  - [ ] Security insights ([_docs_](https://clomonitor.io/docs/topics/checks/#security-insights))
  - [ ] Security policy ([_docs_](https://clomonitor.io/docs/topics/checks/#security-policy))
  - [ ] Self-Assessment ([_docs_](https://clomonitor.io/docs/topics/checks/#self-assessment))
  - [ ] Signed releases ([_docs_](https://clomonitor.io/docs/topics/checks/#signed-releases-from-openssf-scorecard))
  - [ ] Token permissions ([_docs_](https://clomonitor.io/docs/topics/checks/#token-permissions-from-openssf-scorecard))
  
For more information about the checks sets available and how each of the checks work, please see the [CLOMonitor's documentation](https://clomonitor.io/docs/topics/checks/).
